### ISSUE TITLE
Request - Add Battery Minimum SOC and Force Charge SOC input sliders

### ISSUE THREAD

**Issue by 0rangutan** [Pho3niX90/solis_modbus#16]
Would it be possible to add the Battery Minimum SOC and Force Charge SOC values as input sliders, similar to how you have implemented the Backup SOC?

**Comment by Pho3niX90** [comment]
This is available in version 1.1.0

Let me know if it works for you

**Comment by 0rangutan** [comment]
Yes, these are working well for me - much appreciated!
