### ISSUE TITLE
Request - Add ability to configure Battery Charge and Discharge time windows

### ISSUE THREAD

**Issue by 0rangutan** [Pho3niX90/solis_modbus#18]
Might it be possible to add the ability to configure the battery charge and discharge windows within this integration using a simple time picker and submit for each of the available time slots?  The attached screenshot shows these in the Solis Cloud UI.
There is an implementation of this in https://github.com/wills106/homeassistant-solax-modbus but it is not at all user-friendly.
![Screenshot 2023-12-12 at 16 32 07](https://github.com/Pho3niX90/solis_modbus/assets/3738389/7eb8ebf7-0762-4377-9c39-ad31f00656f0)

**Comment by Pho3niX90** [comment]
This is now implemented in `1.2.0`, I have added an example config card here: https://github.com/Pho3niX90/solis_modbus#settings-card-example
