### ISSUE TITLE
PV Power anomaly 

### ISSUE THREAD

**Issue by aavanzyl** [Pho3niX90/solis_modbus#20]
Hi

So I have been running the plugin for a while now and with the last update, I noticed a change in the PV energy.

Here on the graph, you can see its a definite change after the update. 
<img width="1044" alt="image" src="https://github.com/Pho3niX90/solis_modbus/assets/23451086/a752cc02-e232-4cc0-84af-14ea21980598">

The total seems to be closer to the actual. 
<img width="353" alt="image" src="https://github.com/Pho3niX90/solis_modbus/assets/23451086/28795161-461b-4033-a7f7-c78377d393cb">

**Comment by Pho3niX90** [comment]
Will investigate this today. Is the issue only for the individual string values?

**Comment by Pho3niX90** [comment]
could you check `Solis PV Voltage 1` and `Solis PV Current 1`, as one of them would be the offending values.

**Comment by Pho3niX90** [comment]
Can you confirm if `1.2.1` fixes the issue?

**Comment by aavanzyl** [comment]
The Solis PV Voltage 1 & Solis PV Current 1 both match exactly the values directly from the inverter itself. I use the bluetooth connection to connect to the inverter while HA uses the Wifi.

Just looking at immediate values, the inverter indicates 1490,41W and the 14904,1W. It's as if it's just multiplied by the factor of 10. 

Below is a quick screen grab to illustrate the values, they might be taken 10 seconds apart, so the values do fluctuate, but are always very close to each other, so not worry about difference, since the app might only be reading at an different interval. 

Solis Home Assistant             |  Solis Cloud App (Bluetooth)
:-------------------------:|:-------------------------:
![image](https://github.com/Pho3niX90/solis_modbus/assets/23451086/44914336-bd17-4a48-9695-404d2cbf0895)  | ![image](https://github.com/Pho3niX90/solis_modbus/assets/23451086/3cb802bf-ad01-4f1a-9fdc-58cdb4ee5041)

**Comment by aavanzyl** [comment]
> Can you confirm if `1.2.1` fixes the issue?

Checking...

**Comment by aavanzyl** [comment]
Working as expected, thank you :) I owe you a beer.
