### ISSUE TITLE
Bugs with sensors for Battery Charge / Discharge

### ISSUE THREAD

**Issue by 0rangutan** [Pho3niX90/solis_modbus#22]
Possible issues with battery related sensors:
1. The Solis Battery Force-charge Power Limitation sensor reads as 50W in the integration Sensors but 500W in the integration Controls and also Solis Cloud.  So I think out by factor of 10 somewhere?
2. Solis Battery Power is the sensor for the power currently going into the battery to charge it so perhaps this could be re-named to indicate the charging, eg. Solis Battery Charge Power?
3. I can't find an equivalent sensor for power currently being **discharged** from the battery (eg. Solis Battery Discharge Power) - Have I missed this somewhere?

**Comment by Pho3niX90** [comment]
What do you mean by point 3? 
The charge sensor would be `sensor.solis_battery_charge_power` and discharge `sensor.solis_battery_discharge_power`

**Comment by 0rangutan** [comment]
Apologies for any confusion.
Are you saying that I should use sensor.solis_battery_charge_power and sensor.solis_battery_discharge_power ?
Neither are present in my instance of your integration.  Should they be?

Point 3 was requesting that a Battery Discharge sensor be added.

Is the problem that they are missing from my setup or from your integration?

**Comment by Pho3niX90** [comment]
For the other points

1. This is definitely a bug, and will address this. The input `number.` is the correct value.
2. `Battery power` is a signed 32, however, solis just returns this as a positive, direction is determined by `Solis Battery Current Direction`.  if  `Solis Battery Current Direction` == 0, then it's charging, if it's 1, then it's discharging.

**Comment by Pho3niX90** [comment]
I was mistaking about `sensor.solis_battery_charge_power` and `sensor.solis_battery_discharge_power`. It seems I had this as a template sensor in my configuration. I will defnitely add these sensors.

**Comment by 0rangutan** [comment]
Ah, great - that all makes sense now.
Yes please - adding these as sensors in the integration would be very helpful.

**Comment by Pho3niX90** [comment]
So the 2 sensors have been added in `1.3.0`. I am still investigating how to properly handle point 1

**Comment by 0rangutan** [comment]
All working well now, many thanks
