### ISSUE TITLE
its is possible to see the list of entities that this integration show to ha? thanks a lot!!

### ISSUE THREAD

**Issue by kiloptero** [Pho3niX90/solis_modbus#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Pho3niX90** [comment]
The current list can be found here: https://solis-modbus.readthedocs.io/en/latest/sensors.html

**Comment by kiloptero** [comment]
Solis S6 Pro 6kW Advanced Hybrid Inverter
its is possible to share the sku model of the inverter?

**Comment by Pho3niX90** [comment]
The sku would be
S6-EH1P6K-L-PRO

But the code should work for these as well:
S6-EH1P3K-L-PRO
S6-EH1P3.6K-L-PRO
S6-EH1P5K-L-PRO
S6-EH1P6K-L-PRO
S6-EH1P8K-L-PRO

I will be happy to add support for others as well. The code should theoretically already be compatible with all solis inverters.

**Comment by kiloptero** [comment]
thanks for the time to supporting us!

Andres Roepke Del Solar.
Ingeniero Civil Industrial
Ingeniero Electronico
Mobile 88196932
