### ISSUE TITLE
Charge / Discharge Time Slots - Error displaying new selection

### ISSUE THREAD

**Issue by bangorha** [Pho3niX90/solis_modbus#28]
Home Assistant Solis Modbus allows me to change the start/end times for my various charge/discharge slots - for info, I am only using Charging Time Slot 1 and Discharging Time Slot 1, but after refreshing the webpage it reverts to the previously selected times. 

![Home Assistant - Before Page Reload](https://github.com/Pho3niX90/solis_modbus/assets/123200227/86d28ff2-5c39-4794-9ccf-9e3afed578b2)

**After web-browser refresh:**

![Home Assistant - After Page Reload](https://github.com/Pho3niX90/solis_modbus/assets/123200227/b918970b-1a13-4152-b047-2a0df6a0e973)

**Solis Cloud Remote Control - time update successful:**

![Solis Cloud - Remote Control](https://github.com/Pho3niX90/solis_modbus/assets/123200227/541a46d5-6874-4665-8363-9f54f98d233d)

Even though the previous times are displayed, the new times have been successfully written to the Inverter Registers as shown in the Solis Remote Control screenshot, and the system operates as I intended, but for some reason only the original times are displayed after a refresh.

**Comment by Pho3niX90** [comment]
So if I am understanding the issue correctly. The change was written successfully, however, the state of the change wasn't persisted in HA?

**Comment by Pho3niX90** [comment]
So if I am understanding the issue correctly. The change was written successfully, however, the state of the change wasn't persisted in HA?

**Comment by bangorha** [comment]
> So if I am understanding the issue correctly. The change was written successfully, however, the state of the change wasn't persisted in HA?

Yes that's correct - the change happens instantaneously, as I am able to observe the relative increase in import / export as soon as I apply the figures.

An immediate check on Solis Cloud shows the correct new times, but when I refresh the web browser, the HA Dashboard times have reverted to what they were previously.

For now I have removed the solis-modbus integration and am trialling the solax integration - the issue is not prevalent when using the Solax integration.

**Comment by Pho3niX90** [comment]
Okay perfect, thanks for letting me know. Will add a fix in the next day

**Comment by Pho3niX90** [comment]
This is now fixed in `1.3.2`
