### ISSUE TITLE
Solis missing Total Charche Battery

### ISSUE THREAD

**Issue by fastsonic** [Pho3niX90/solis_modbus#34]
Hi, 
i miss the :
33161_Battery_Total_Charge_energy
in my entities

Discharte is present with:
33165_Battery_Total_Discharge_energy

Gerät Informationen
S6
von Solis
Firmware: 1.3.3

All other Entities ( 146) are present

**Comment by fastsonic** [comment]
![image](https://github.com/Pho3niX90/solis_modbus/assets/18059809/386ecfe5-08e1-4674-9296-892ec19974ae)

**Comment by Pho3niX90** [comment]
available in `1.3.4`
