### ISSUE TITLE
Unit maybe wrong Solis Active Power

### ISSUE THREAD

**Issue by fastsonic** [Pho3niX90/solis_modbus#38]
Solis 1.3.5
Solis RHI 5k-48

Solis Acitive Power: Unit is W but from Solis come KW so the Measurement ist to low.
Not sure its only for 5k-48 or also  for the Solis 6 !?

:
I changed it Hass.io with yaml:

homeassistant:
  customize:
    sensor.solis_active_power:
      unit_of_measurement: "kW"

**Comment by Pho3niX90** [comment]
Accordingly to the documentation, it's definitely sent as watts. It seems the issue was around the unit multiplier that accidentally turned it into a kw figure. Will fix shortly.
