### ISSUE TITLE
Configuring the Energy Dashboard

### ISSUE THREAD

**Issue by aavanzyl** [Pho3niX90/solis_modbus#4]
Hello,

I own a Solis S6 Pro 5kw inverter equipped with an S2_WL_ST wifi data logger, which appears to be identical to the one you've successfully set up.

I've managed to establish a connection between the inverter and Home Assistant, allowing me to view all the data from the inverter. However, I'm having difficulty determining which sensor should be integrated into the Energy Dashboard to monitor solar energy production. Could you provide some guidance on this?

This is an amazing project, it leaps ahead of the hardware-based integrations requiring a Pi or ESP.

<img width="1023" alt="image" src="https://github.com/Pho3niX90/solis_modbus/assets/23451086/510e96a2-b5f8-49c0-8f9c-92550a3f57bb">
<img width="1094" alt="image" src="https://github.com/Pho3niX90/solis_modbus/assets/23451086/9db08456-7cea-4e96-b860-84f33e6c783c">

**Comment by Pho3niX90** [comment]
Hi 

For grid consumption:
 
 CT Meter:
` sensor.solis_inverter_meter_total_active_power` - This tracks both import and export

Solar Panels:
`sensor.solis_inverter_total_dc_output` this would be the total solar output in W

I haven't tested the solar myself as yet, but should be working as expected.

**Comment by Pho3niX90** [comment]
I have added an example yaml for the solar card as well: https://github.com/Pho3niX90/solis_modbus/tree/1.0.6#sunsynk-solar-card-setup

**Comment by aavanzyl** [comment]
The `sensor.solis_inverter_total_dc_output` is measured in watts with a device class of `POWER`. I think due to this it does not show up on the list of entities to choose as `Solar Production Energy` on the energy dashboard. 

Reading up on some docs, it seems that adding the code below would convert the watt to kWh. The input only works with GJ, kWh, MJ, MWh, Wh. 
```
sensor:
    - platform: integration
      source: sensor.solis_inverter_total_dc_output
      name: solis_inverter_total_pv_yield
      unit_prefix: k
      round: 2
```

The same for the `sensor.solis_inverter_meter_total_active_power` sensor.

**Comment by Pho3niX90** [comment]
Aah yes, completely forgot that HA energy dash uses meters. I disabled mine and just created one that is realtime. 

I will add a meter sensor
