### ISSUE TITLE
Solis Total Battery Charge Energy and Discharge Energy seems to be wrong 

### ISSUE THREAD

**Issue by fastsonic** [Pho3niX90/solis_modbus#44]
Version 1.4.0

Solis RHI 5k

Solis Total Battery Charge Energy
Solis Total Battery Discharge Energy

shows      195,1kWh
has to be  1951kWh

Solis Today Battery Charge and discharge are correct.

**Comment by Pho3niX90** [comment]
thanks for letting me know
