### ISSUE TITLE
Not working, TCP port required

### ISSUE THREAD

**Issue by HectorJRL** [Pho3niX90/solis_modbus#49]
Hi there! 
I'm trying to make this work with my Solis inverter, but I'm stuck at the beginning of the process.
After writing the inverter IP (doble checked that it's the right one), and NOT changing the tcp port by defect (502), it gives me an "unknown error ocurred".

![Captura de pantalla 2024-04-04 204200](https://github.com/Pho3niX90/solis_modbus/assets/139003140/beb51317-bbea-48e2-9b89-544d490a7b9a)

I guess it's a simple mistake, but I can't find the way to figure out the proper tcp port.

Any help will be really appreciated.

**Comment by Pho3niX90** [comment]
the ip should not contain http://, just the ip
192.168.1.65

**Comment by HectorJRL** [comment]
Sorry for the delay. I had to finish the solar panel instalation on the roof itself, and that took all my free time.

Same result removing the http, sadly...
