### ISSUE TITLE
HA 2024.5 plugin not working

### ISSUE THREAD

**Issue by cgilis** [Pho3niX90/solis_modbus#53]
**Describe the bug**
Since the update to 2024.5 the plugin is not working anymore.

```
This error originated from a custom integration.

Logger: pymodbus.logging
Source: custom_components/solis_modbus/modbus_controller.py:24
integration: Solis Modbus (documentation, issues)
First occurred: May 1, 2024 at 21:47:29 (4 occurrences)
Last logged: May 1, 2024 at 22:01:27

Failed to connect
```

```
This error originated from a custom integration.

Logger: custom_components.solis_modbus.modbus_controller
Source: custom_components/solis_modbus/modbus_controller.py:26
integration: Solis Modbus (documentation, issues)
First occurred: May 1, 2024 at 21:47:29 (4 occurrences)
Last logged: May 1, 2024 at 22:01:27

Failed to connect to Modbus device. Will retry, failures = 1
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: May 1, 2024 at 21:47:29 (4 occurrences)
Last logged: May 1, 2024 at 22:01:27

Error setting up entry Solis: 192.168.*.*** for solis_modbus
Traceback (most recent call last):
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 26, in connect
    raise _LOGGER.warning(f"Failed to connect to Modbus device. Will retry, failures = {self.connect_failures}")
TypeError: exceptions must derive from BaseException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solis_modbus/__init__.py", line 66, in async_setup_entry
    await controller.connect()
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 32, in connect
    raise _LOGGER.error(f"Failed to connect to Modbus device. Will retry")
TypeError: exceptions must derive from BaseException
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yurix2019** [comment]
I’ve also had this issue. No sensors reporting, no numeric state changes accepted.

**Comment by Pho3niX90** [comment]
Investigating

**Comment by 0rangutan** [comment]
Same issue here

**Comment by Pho3niX90** [comment]
@0rangutan @cgilis @yurix2019 could you confirm if release 1.4.7 solves the issue for you

**Comment by cgilis** [comment]
> @0rangutan @cgilis @yurix2019 could you confirm if release 1.4.7 solves the issue for you

Confirmed working on **2024.4.4** and **2024.5**

Thx @Pho3niX90 for the fast fix! 🦸‍♂️

**Comment by yurix2019** [comment]
<img width="1366" alt="Screenshot 2023-07-05 at 08 58 17" src="https://github.com/Pho3niX90/solis_modbus/assets/112395870/0e75fa35-1968-4acb-acc1-54644048dcc7">
Thanks for hard work. I’m on 2024.6 and most things are working for me with the exception of the charge/discharge amps and times (see screen grab).

**Comment by Pho3niX90** [comment]
> <img width="1366" alt="Screenshot 2024-05-03 at 07 58 33 jpeg" src="https://github.com/Pho3niX90/solis_modbus/assets/112395870/a5633e45-cf25-428b-9469-3e33abff909c">
> 
> Thanks for hard work. I’m on 2024.5 and most things are working for me with the exception of the charge/discharge amps and times (see screen grab).

I created a separate issue for this, as it seems it might have been broken in the last release as well?

**Comment by 0rangutan** [comment]
Fixed for me here, thanks @Pho3niX90

**Comment by yurix2019** [comment]
For me it was more or less working on the core release before 2024.5. There were some anomalies with the charge and discharge amps defaulting to 50 amps, but I had work around automations to reset to zero when I wasn’t charging or discharging.

**Comment by Pho3niX90** [comment]
@yurix2019 1.4.8 should have the amps fixed

**Comment by yurix2019** [comment]
Thanks so much. It’s now working well.

This integration is useful and it saves me using the Solis Cloud app (not the greatest) or having to climb into my loft twice a day, so thanks again.

**Comment by cgilis** [comment]
Hey @Pho3niX90 i think it’s back after 2024.5.1 🥲

**Comment by Pho3niX90** [comment]
> Hey @Pho3niX90 i think it’s back after 2024.5.1 🥲

I am running core 2024.5.1 without issues

**Comment by cgilis** [comment]
This is in the logs:

```
Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: 07:53:55 (2 occurrences)
Last logged: 10:08:41

Error setting up entry Solis: 192.168.1.*** for solis_modbus
Traceback (most recent call last):
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 25, in connect
    raise _LOGGER.warning(
TypeError: exceptions must derive from BaseException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solis_modbus/__init__.py", line 65, in async_setup_entry
    await controller.connect()
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 32, in connect
    raise _LOGGER.error(f"Failed to connect to Modbus device. Will retry")
TypeError: exceptions must derive from BaseException
```

**Comment by Pho3niX90** [comment]
> Traceback (most recent call last):

Ware you trying to setup a new connection? Or was this just on restart?

**Comment by cgilis** [comment]
> > Traceback (most recent call last):
> 
> Ware you trying to setup a new connection? Or was this just on restart?

Just on restart after I did the update to 2024.5.1.
Do I try to remove it and add the solis again?
