### ISSUE TITLE
Values Jumpe to zero and Back after restart Homeassistant

### ISSUE THREAD

**Issue by fastsonic** [Pho3niX90/solis_modbus#57]
not sure if i herer right..
Solis RHI6k
All updates installed today for Solis Plugin and HA Core.
After Restart of Homeassistant all(most)  Statistiks from Solis Plugin, seams to be send a short 0 ( there is an gap)  bevor become normal values.
So the Energy Dashboard jumps down and count new.
Workaround is to create a filtered Entity but searching for the right Point to eliminate the Problem. And there are a lot from this Plugin.
Is it possible to fix it from this side ?
Thanks

**Comment by 0rangutan** [comment]
I think I have seen this too.
I wasn't aware of the specific cause, but after any HA restart my energy graphs relating to the Solis plugin get messed up.

**Comment by fastsonic** [comment]
you can see and fix the Jumps under the Statistik, here we have after the Restart ( and some minits running time ) a negativ Value with the High of the  counter.
After each restart i edit  all Counters and delete the negative Entries.

**Comment by Pho3niX90** [comment]
I will investigate this issue. It's probably related to no modbus data being available during initializing sensors, but it's suppose to use the last state.

**Comment by Pho3niX90** [comment]
Could you test if 1.4.9 resolves the issue

**Comment by 0rangutan** [comment]
Yes, fixed for me.  Applied 1.4.9, restarted HA, all stats look correct.
Many thanks!

**Comment by 0rangutan** [comment]
Spoke too sorry...
The issue results in the whole day's worth of statistics so far being considered part of fhe last hour, eg.
![Screenshot_20240504_130642_Home Assistant](https://github.com/Pho3niX90/solis_modbus/assets/3738389/cd1c76ea-9d79-4f3c-8cc1-4b6382109653)

**Comment by fastsonic** [comment]
Me also ,
in the first Moment i think its fixed but still present. Will try some reboots, to give a better Overview

**Comment by Pho3niX90** [comment]
I am hoping this is now fixed in `1.5.0`, please let me know

**Comment by fastsonic** [comment]
I think you did it. 
2 restart so far no neegative values !
Check later again and give an update

**Comment by fastsonic** [comment]
Fixed for me.
Thanks a lot!
