### ISSUE TITLE
Wanted to install a new installation

### ISSUE THREAD

**Issue by cgilis** [Pho3niX90/solis_modbus#60]
**Describe the bug**
Hi @Pho3niX90 ,

I have a new installation where I want to add this nice plugin.
But I always get this error:

![CleanShot 2024-05-16 at 17 32 15@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/1c1b9a77-9cf9-47f3-a1c8-4bd2a728ac9a)

Here is the error log:
```
This error originated from a custom integration.

Logger: custom_components.solis_modbus.modbus_controller
Source: custom_components/solis_modbus/modbus_controller.py:32
integration: solis_modbus (documentation, issues)
First occurred: 17:32:05 (14 occurrences)
Last logged: 17:36:53

Failed to connect to Modbus device. Will retry
```

```
This error originated from a custom integration.

Logger: custom_components.solis_modbus.modbus_controller
Source: custom_components/solis_modbus/modbus_controller.py:25
integration: solis_modbus (documentation, issues)
First occurred: 17:32:05 (14 occurrences)
Last logged: 17:36:53

Failed to connect to Modbus device. Will retry, failures = 1
```

```
This error originated from a custom integration.

Logger: pymodbus.logging
Source: custom_components/solis_modbus/modbus_controller.py:23
integration: solis_modbus (documentation, issues)
First occurred: 17:32:05 (14 occurrences)
Last logged: 17:36:53

Failed to connect [Errno 111] Connect call failed ('192.168.0.128', 502)
Failed to connect [Errno 111] Connect call failed ('192.168.0.101', 502)
Failed to connect [Errno -2] Name does not resolve
Failed to connect [Errno 111] Connect call failed ('192.168.0.191', 502)
```

Full log:
[home-assistant_2024-05-16T15-44-35.549Z.log](https://github.com/Pho3niX90/solis_modbus/files/15337677/home-assistant_2024-05-16T15-44-35.549Z.log)

**Comment by cgilis** [comment]
Looks like the same error in #49

**Comment by Pho3niX90** [comment]
Will investigate the reason behind this. Will have to check how I can reproduce this without losing my data on my installation 😅

**Comment by cgilis** [comment]
> Will investigate the reason behind this. Will have to check how I can reproduce this without losing my data on my installation 😅

Super @Pho3niX90 !! Would it help to give you access to my test server?
Can you contact me by mail, so I can share the credentials? --> Christoffel@me.com

**Comment by Pho3niX90** [comment]
Also, if you enter the IP into a browser window, can you reach the inverters' web interface?

**Comment by cgilis** [comment]
Is something I cannot test right now, because it's on a remote server 🥲

**Comment by cgilis** [comment]
Will go to the remote location tomorrow morning and will report back!

**Comment by cgilis** [comment]
![CleanShot 2024-05-16 at 22 33 07@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/8f38bd8e-6179-4c8c-8f83-98ebafeccc37)

@Pho3niX90 with VPN it worked the ip is 192.168.0.101

**Comment by Pho3niX90** [comment]
> ![CleanShot 2024-05-16 at 22 33 07@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/8f38bd8e-6179-4c8c-8f83-98ebafeccc37)
> 
> @Pho3niX90 with VPN it worked the ip is 192.168.0.101

To be clear, the HA device trying to access the solis is on the same network right? Will send you an email for access.

**Comment by cgilis** [comment]
@Pho3niX90 after updating the firmware of the Solis, the problem is fixed and is now visible in HA.
Do you still want to check how you can fix it on older firmwares?

**Comment by Pho3niX90** [comment]
> @Pho3niX90 after updating the firmware of the Solis, the problem is fixed and is now visible in HA.
> Do you still want to check how you can fix it on older firmwares?

Aah perfect. I need to note it down, I remember reading that one of the firmwares did have a modbus comms issue.

**Comment by cgilis** [comment]
Hi @Pho3niX90 ,

The same error occurred with an updated Solis.
![CleanShot 2024-07-10 at 13 29 33@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/5be52e7a-5e94-489c-87bd-93c405c6ad72)

The log file is here:
[home-assistant_2024-07-10T11-28-48.353Z.log](https://github.com/user-attachments/files/16160032/home-assistant_2024-07-10T11-28-48.353Z.log)

Any idea?

**Comment by Pho3niX90** [comment]
> Hi @Pho3niX90 ,
> 
> The same error occurred with an updated Solis.
> ![CleanShot 2024-07-10 at 13 29 33@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/5be52e7a-5e94-489c-87bd-93c405c6ad72)
> 
> The log file is here:
> [home-assistant_2024-07-10T11-28-48.353Z.log](https://github.com/user-attachments/files/16160032/home-assistant_2024-07-10T11-28-48.353Z.log)
> 
> Any idea?
> 
> 
> Fyi, i can ping the solis:
> ![CleanShot 2024-07-10 at 13 31 10@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/d75a9f3f-3c0f-47bf-8eb4-6dcce11dcc7e)
> 

Strange. The ping seems fine, but the logs state it couldn't open a connection. I am wondering if the modbus port isn't occupied, the only way to release it is to restart the dongle. 

Perhaps try removing the integration completely, restart and install again?

**Comment by cgilis** [comment]
I've tried removing the integration and did not work.
Also tried restarting the solis, but was the same error..

**Comment by cgilis** [comment]
The solis is also on the latest update (web ver: 2.4.0)
And I see there is a MQTT integration now, is that something we can try? 
![CleanShot 2024-07-10 at 13 47 37@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/34045e27-16f2-42dc-a4a7-3cf1355d31a0)

**Comment by Pho3niX90** [comment]
The plugin doesn't have mqtt support, as that is something  completely different. 

Will need to try to see if the port is still 502 on the new version, as it's possible that they have changed it. I will need yo request an update on my system to test with the same version.

**Comment by Pho3niX90** [comment]
> I've tried removing the integration and did not work.
> Also tried restarting the solis, but was the same error.. not sure if the wifi stick restarts when the solis restarts.. :-) 

Not entirely sure. If power is reset to the stick, it should. The best is to hold in the button on it to restart.

**Comment by cgilis** [comment]
> The plugin doesn't have mqtt support, as that is something completely different.
> 
> Will need to try to see if the port is still 502 on the new version, as it's possible that they have changed it. I will need yo request an update on my system to test with the same version.

If you need I can give you access to the HA to test it.. let me know.

**Comment by Pho3niX90** [comment]
> I have another inverter on 2.4 and that still works with your plugin @Pho3niX90 so I think the port hasn't changed.

What's the difference between the 2?

**Comment by Pho3niX90** [comment]
> > > I have another inverter on 2.4 and that still works with your plugin @Pho3niX90 so I think the port hasn't changed.
> > 
> > What's the difference between the 2?
> 
> No difference between them, strange :( 
> I've restarted the dongle, but there's no difference.

So can you explain the setup to me so that I can mimick it my side? 

Are both connecting to same HA instace?
Are the connected ad mater / slave, or independent from oneanother? 
Are they on the same network? 
What else can you tell me?

**Comment by cgilis** [comment]
> > > > I have another inverter on 2.4 and that still works with your plugin @Pho3niX90 so I think the port hasn't changed.
> > > 
> > > 
> > > What's the difference between the 2?
> > 
> > 
> > No difference between them, strange :(
> > I've restarted the dongle, but there's no difference.
> 
> So can you explain the setup to me so that I can mimick it my side?
> 
> Are both connecting to same HA instace? Are the connected ad mater / slave, or independent from oneanother? Are they on the same network? What else can you tell me?

So can you explain the setup to me so that I can mimick it my side?

Are both connecting to same HA instace?
Nope, those are separate homes with separate HA / Inverters
Are the connected ad mater / slave, or independent from oneanother?
Are they on the same network?
Nope different location.
What else can you tell me?
It's exactly the same setup, but in a different location.

**Comment by cgilis** [comment]
@Pho3niX90 I've tried now on another location with another Solis inverter (now not on a non hybrid one) and this one is also not connecting.. strange.

**Comment by Pho3niX90** [comment]
@cgilis are you able to give me access to one of these systems then I can do some diagnostics? If you have discord, send me a message @ pho3nix90

**Comment by cgilis** [comment]
> @cgilis are you able to give me access to one of these systems then I can do some diagnostics? If you have discord, send me a message @ pho3nix90

Great! My profile is cgilis, just send you a message.
