### ISSUE TITLE
Batterie Current Direction is not working

### ISSUE THREAD

**Issue by fastsonic** [Pho3niX90/solis_modbus#61]
Hi,
Device: Solis RHI5k-48
I thinks since an update around 6.05 i lost the Batterie current direction.

I already reboot the Solis other Values are working normally.
can you please take a look for it ?
Thanks
![Screenshot 2024-05-28 082658](https://github.com/Pho3niX90/solis_modbus/assets/18059809/d1bd3573-9e25-41d3-a7f0-050ef1064e0c)

**Comment by Pho3niX90** [comment]
@fastsonic can you try the new release, and see if that resolves the issue?

**Comment by fastsonic** [comment]
Fixed for me. Thanks again
