### ISSUE TITLE
HA 2024.6 plugin not working

### ISSUE THREAD

**Issue by cgilis** [Pho3niX90/solis_modbus#69]
**Describe the bug**
Hey @Pho3niX90, i'm a bit late to test this, but it was not working on 2024.6?
I've now downgraded back to 2024.5 and its working fine :-)

But 2024.7 is almost coming that's why I'm reporting this :-)

**Comment by matthewbyrne** [comment]
I thought the same, but then I updated the plugin in HACS and gave it restart and it's working again.

Running 2024.05.7 with HA version 2024.6.4

**Comment by cgilis** [comment]
> I thought the same, but then I updated the plugin in HACS and gave it restart and it's working again.
> 
> Running 2024.05.7 with HA version 2024.6.4

If I check for updates I don't see one in Hacs.. 😢

**Comment by Pho3niX90** [comment]
> **Describe the bug** Hey @Pho3niX90, i'm a bit late to test this, but it was not working on 2024.6? I've now downgraded back to 2024.5 and its working fine :-)
> 
> But 2024.7 is almost coming that's why I'm reporting this :-)

this is strange, I am on 2024.6.4 without issues.

**Comment by cgilis** [comment]
Ok will try again :)

**Comment by cgilis** [comment]
Here it's not working @Pho3niX90 , strange.
The log file is here:
[home-assistant_2024-07-03T11-55-59.294Z.log](https://github.com/user-attachments/files/16083203/home-assistant_2024-07-03T11-55-59.294Z.log)

**Comment by matthewbyrne** [comment]
You can hit 192.168.1.247 from your HA instance, right? 

Try `telnet 192.168.1.247 502`. That's the modbus port

**Comment by cgilis** [comment]
> You can hit 192.168.1.247 from your HA instance, right?
> 
> Try `telnet 192.168.1.247 502`. That's the modbus port

![CleanShot 2024-07-03 at 15 59 09@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/2764faed-fdce-44b5-8cad-7c86ff7a62c3)
This is what i get.. hmmm

**Comment by Pho3niX90** [comment]
> running

Those response time might be causing timeouts, default, I think is 4seconds.

Did something change in your networking that might be causing the major delays? You could try and restart your network hardware, and perhaps, choose a less congested wifi channel.

Either way, will see if I can add in some logic to retry at longer timeouts.

**Comment by cgilis** [comment]
> > running
> 
> Those response time might be causing timeouts, default, I think is 4seconds.
> 
> Did something change in your networking that might be causing the major delays? You could try and restart your network hardware, and perhaps, choose a less congested wifi channel.
> 
> Either way, will see if I can add in some logic to retry at longer timeouts.

Strange, nothing changed, if i downgrade back to 2024.5 it works perfectly..
Will reboot my router.. and try again

**Comment by cgilis** [comment]
![CleanShot 2024-07-03 at 17 08 28@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/714732f0-2422-4d2b-aa6c-a0ca135c15d2)

Did reboot of the wifi stick of Solis, and now its working in HA.. crazy :-)
Thx @Pho3niX90 & @matthewbyrne

**Comment by cgilis** [comment]
Same issue on 2024.7
Strange 😅

**Comment by cgilis** [comment]
Strange now its back, took some time... if you need the logs let me know @Pho3niX90

**Comment by Pho3niX90** [comment]
> Strange now its back, took some time... if you need the logs let me know @Pho3niX90 

Can you grab logs and then restart stick again?

**Comment by cgilis** [comment]
> > Strange now its back, took some time... if you need the logs let me know @Pho3niX90
> 
> Can you grab logs and then restart stick again?

[home-assistant_2024-07-04T07-50-47.370Z.log](https://github.com/user-attachments/files/16095201/home-assistant_2024-07-04T07-50-47.370Z.log)
Is this ok?
