### ISSUE TITLE
unknown error occured at connection trial to Solis rai-3k-48es-5 internal wlan

### ISSUE THREAD

**Issue by stefeis** [Pho3niX90/solis_modbus#72]
I´m not able to connect to rai-3k-48es-5 at internal wlan adapter => unknown error occured. 
using solax modbus integration this adapter is no problem (but I would like to use your integration :-))
BUT: at solax modbus integration I can set Modbus RTU over TCP - propably this is the big difference?

I tried several ports (it´s possible to modify at the internal wlan adapter), but no success.

if I´m right, the Solis S3 stick is just useable for cloud connections, which I don´t like.
you tested with Solis S2, but thisone I don´t have. any other suggestions for other modbus modules?
I also test an esphome solution base on a wemos D1 mini, which works fine, but does not offer your features and I´m no developer so I prefer to use ready made solutions :-)

Core 2024.9.1
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240906.0

logfile: 
Logger: custom_components.solis_modbus.modbus_controller
Quelle: custom_components/solis_modbus/modbus_controller.py:42Failed to read Modbus register: Modbus Error: [Input/Output] ERROR: No response received after 3 retries

any ideas?

thanks a lot :-)
stefan

**Comment by Pho3niX90** [comment]
@stefeis you need to disable solax integration first. 

The wifi dongle can only accept a single connection at a time, anything afterwards will just error.
