### ISSUE TITLE
PV_3 and PV_4 power

### ISSUE THREAD

**Issue by Pauliuxliux** [Pho3niX90/solis_modbus#81]
Hello, I have solis S6 with 4 mppt, and I connected 3 of them. Can you update integration to calculate PV_3 and PV4 power. Best regards.

**Comment by Pho3niX90** [comment]
> Hello, I have solis S6 with 4 mppt, and I connected 3 of them. Can you update integration to calculate PV_3 and PV4 power. Best regards.

Which solis is this exactly, so that I can get the spec information.

**Comment by Pauliuxliux** [comment]
Hi, solis s6-eh3p12k-h. My hass shows PV3 and PV4 current and voltage. I
think you need only update calculation part. thank you in advance.

**Comment by Pho3niX90** [comment]
@Pauliuxliux the latest release should have pv3 and 4
